- src/Table.jsx
- src/TableRow.jsx
把展开按钮从表格第一个字段里分离开来，[需求](https://github.com/ant-design/ant-design/issues/241)
方法：row 第一列添加 td 放置展开按钮，并在表头内第一个位置添加一个空的 td ，
> separate expand icon

- src/Table.jsx
This PR optimizes the row expanding procedure and deal better with rendering `React` components in the `expandedRowRender` function by:
* reducing the number of calls to determine if the same row is expanded inside the same `render`,
* only calling the `expandedRowRender` function when the row is expanded.
* this way, a react component mounted here will have the `componentDidMount` and `componentWillUnmount` methods correctly called.
It also, fixes an *linting* error present in the `master` branch
> Optimize row expanding

- HISTORY.md
- README.md
- examples/colspan-rowspan.js
- src/Table.jsx
- src/TableRow.jsx
- tests/index.spec.js
增加以下特性：
1.  表头支持列合并
2.  单元格占多行
3.  单元格占多列
API变动：
```js
columns = [{
title: '列一',
dataindex: '',
headerColSpan: 2, // 列头占两列
render(value, record, index) {
return {
children: value,  // 单元格内容
props: {
align: 'right' // 向右对齐
colspan: 2, // 单元格占两列
rowspan: 2 // 单元格占两行
}
};
}
}]
```
> Feature colspan rowspan

- README.md
- examples/colspan-rowspan.js
- src/TableRow.jsx
1、删除给 `td`  设置的 `align` 属性
2、优化表格合并的例子
> del align, optimize the demo of colspan-rowspan

- README.md
- examples/expandedRowRender.js
- src/Table.jsx
This PR adds the ability to manage the expanded row keys externally, by passing the keys of the rows that should be expanded as `expandedRowKeys` prop, and being notified on changes with the prop function `onExpandedRowsChange`.
It also, does not break the interface as it is backwards compatible. If none of these props are passed into the component, it will continue with the previous behaviour of storing the expanded rows in the internal state.
Further:
* New features were shown off in the `examples/expandedRowRender.js`
* New features were documented in the README.md
> Manage expanded row keys externally

- src/TableRow.jsx
Fix problem below, which is work in old version.
```js
var columns = [{
title: 'xx',
render() {
return 'raw text without wrapping';  // It is broken in 3.6
}
}]
```
> read text.children when there is children in text

- examples/className.js
- examples/colspan-rowspan.js
- examples/dropdown.js
- examples/expandedRowRender.js
- examples/key.js
- examples/scrollBody.js
- examples/simple.js
- examples/subTable.js
- src/Table.jsx
- src/TableRow.jsx
1. 为 children 上的节点增加缩进，默认每级 `15px`
```jsx
var data = [{
key: 1,
name: 'indent0',
children: [{
key: 6,
name: 'indent1'
}, {
key: 7,
name: 'indent1',
children: [{
key: 8,
name: 'indent2'
}]
}]
}] 
<Table data = {data} indentSize = {40}/>
```
> [feat] add indent for data.i.children...children

- assets/index.less
- src/Table.jsx
- src/TableRow.jsx
当 data.i.children.length 时，给无法展开的行增加占位元素
> [refine] add spaced element

- examples/rowClick.js
- src/Table.jsx
- src/TableRow.jsx
使用方法：
```
const onRowClick = function(record, index){}
<Table onRowClick={onRowClick} />
```
1. `this` 指向 `<TableRow />`
2. `index` 代表在 `father.children` 里面的 `index`，不是在所有 `row` 的 `index`
fix ant-design/ant-design#355
fix ant-design/ant-design#767
> [feat] add onRowClick

- src/Table.jsx
一开始调试得到的公式是
```
Math.ceil((columnsPageRange[1] - columnsPageRange[0] + 1) / columnsPageSize) - 1;
```
最后 提交的时候 觉的下面的和上面的公式是等价的 没测试换了
```
Math.floor((columnsPageRange[1] - columnsPageRange[0] + 1) / columnsPageSize);
```
最近调试的时候突然发现不对了。。。现在更正过来。
> fix paging columns bug

- src/ExpandIcon.jsx
- src/TableCell.jsx
- src/TableRow.jsx
Fix ant-design/ant-design#2540 and ant-design/ant-design#2454
Also improve perfermance for #35
> split TableRow and TableCell for better perfermance

- src/Table.jsx
没有  fixed columns 的时候可以减少一次 render。
> call syncFixedTableRowHeight only if any columns fixed

- assets/index.less
- examples/grouping-columns.js
- src/Table.jsx
- tests/GroupingColumns.spec.js
- tests/index.js
#73 
实现了基本的表头合并，还需要看看一些特殊情况的处理。
> Grouping columns

- README.md
- examples/rowClick.js
- src/Table.jsx
- src/TableRow.jsx
> support onRowDoubleClick

- assets/index.less
- src/Table.jsx
- tests/groupingColumnTitle.spec.js
原来用 CSS 的计算方式是有问题的，因为表头可能被里面的内容撑得超过 CSS 计算的高度。
另外有两个疑问：
- [这里](https://github.com/react-component/table/blob/6a5debb0a8fc155287715fa685ce243a6ce2cf1e/src/Table.jsx#L614) 什么情况下会有 `row.getBoundingClientRect().height == false` ?
- [这里](https://github.com/react-component/table/blob/6a5debb0a8fc155287715fa685ce243a6ce2cf1e/src/Table.jsx#L623-L628) 为什么要用 `setTimeout`，这样会导致在测试里没法同步拿到设置的高度。
> 调整合并表头的高度计算

- src/Table.jsx
https://github.com/ant-design/ant-design/issues/3096
垂直滚动的时候不要去更新`scrollPostion`，减少组件的渲染。
> Optimize scrolling

- src/ColumnManager.js
- src/Table.jsx
- src/TableRow.jsx
- tests/ColumnManager.spec.js
- tests/index.js
1. 把所有 columns 相关的计算都抽出来，并对计算结果进行缓存，避免每次都生成新的 columns 对象；
1. 不直接给 TableRow 传 style，避免每次都生成新的 style 对象。
这样改完后发现 #95 其实不需要了， shouldComponentUpdate 可以正常工作了。
> Optimize shouldComponentUpdate

- src/Table.jsx
- src/TableRow.jsx
- src/createStore.js
- tests/createStore.spec.js
- tests/index.js
写了个类似 redux 的 store，把 hover 状态提了出来，这样 hover 状态变化的时候就不需要渲染整个 Table 了。
https://github.com/ant-design/ant-design/issues/3096
> Extract hover state by creating a global state

- examples/jsx.js
- src/Column.jsx
- src/ColumnGroup.jsx
- src/ColumnManager.js
- src/Table.jsx
- src/index.js
- tests/ColumnManager.spec.js
有个问题就是原来 columns 里的 key 不能直接用在 `<Column />` 里了，会访问不到，我暂时用 `colKey` 代替了，或者有更好的处理方法？ @afc163
> JSX column API

- README.md
- package.json
- src/Table.jsx
- src/TableRow.jsx
- src/utils.js
Related https://github.com/ant-design/ant-design/pull/4185
> Add warning for undefined row key.

- package.json
- src/Table.jsx
This patch improves table horizontal scroll performance, https://github.com/ant-design/ant-design/issues/4631
> Use component-classes for className manipulation

- src/Table.jsx
- tests/Table.fixedColumns.spec.js
- tests/Table.spec.js
fix [ant-design #4836](https://github.com/ant-design/ant-design/issues/4836)
然后在写测试时发现使用`enzyme` 渲染组件，[无法获取元素的宽高](https://github.com/airbnb/enzyme/issues/49#issuecomment-270250193)，所以就没补上测试。
> If <Table /> is hidden, don't recalculate rowHeight.

- assets/index.less
- src/Table.jsx
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
antd 本地可重现 http://127.0.0.1:8001/components/table/#components-table-demo-fixed-columns-header
> fix: should not rely on z-index

- assets/index.less
- examples/fixedColumnsWhenResize.js
- src/Table.jsx
- tests/Table.fixedColumns.spec.js
根据这里的例子 https://github.com/ant-design/ant-design/issues/4965#issuecomment-281287015 优化了样式效果。
1. 当不需要滚动条时，不应该出现阴影。
2. 随着 React 组件变化和窗口大小变化，阴影效果动态响应。
3. 修正了自带样式的一些小问题。
> scroll className should change as table width is changed

- src/Table.jsx
Fix https://github.com/ant-design/ant-design/issues/4893
假设有 `<Table columns={columns} data={data} scroll={{ y: 300 }} />`，当数据量很少的时候，table 的高度实际上达不到 300px，但是在 fixed table 上设置了 `height="300px"`，导致 scroll table 的滚动条被 fixed table 挡住。
> Set maxHeight to inner body

- src/Table.jsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
We usually pass a string (or React node) instead of function to the "emptyText" prop, it will be great if the "emptyText" prop can accept either node or function type.
> The "emptyText" prop can either be one React node or a function that returns one React node

- src/TableRow.jsx
close https://github.com/ant-design/ant-design/issues/6775
> fix: onRowMouseEnter onRowMouseLeave is not a function

- README.md
- src/Table.jsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
**Summary**
This is a fix for this issue https://github.com/react-component/table/issues/162
New feature to let Table deal with strings values in 'rowClassName' property so make code become easier in some implementations.
> Issue 162: rowClassName should accept strings too, not just functions

- README.md
- src/Table.js
- tests/Table.spec.js
This PR adds an id property to the root table div, simplifying automated browser testing with multiple table instances on one page.
**current behavior**
_table:_ document.querySelectorAll(div.rc-table>table)**[nth]**
_title  :_ document.querySelectorAll(div.rc-table>.rc-table-title)**[nth]**
**afterwards**
_table :_ document.querySelector(#id>table)
_title :_ document.querySelector(#id>.rc-table-title)
> Add id property to container div

- src/ExpandableTable.js
Ideally no columns should probably exit the entire table creation process and instead just render out the box saying no headers or something along that line. However given how unlikely / infrequent this specific case is I think this is an okay solution to allow expandable tables to have the columns updated later by dynamic content and prevent an error.
In reference to Antd issue 8941:
https://github.com/ant-design/ant-design/issues/8941
> If no columns there is nothing to perform the unshift against.

- assets/index.less
- examples/columnFooter.js
- src/BaseTable.js
- src/BodyTable.js
- src/Column.js
- src/FootTable.js
- src/HeadTable.js
- src/Table.js
- src/TableFooter.js
This is an update on previous PR #191 at @yesmeck's suggestion. 
See discussion here: https://github.com/ant-design/ant-design/issues/5710#issuecomment-368768114
> New API: `column.footer` to render an extra footer row inside table

- examples/expandIcon.js
- src/ExpandableRow.js
- src/ExpandableTable.js
- tests/Table.expandRow.spec.js
- tests/__snapshots__/Table.expandRow.spec.js.snap
This has the same changes as #187, but also includes the unit tests and examples.
This PR allows for overriding the default expand icon.
> feature: add expandIcon

- src/Table.js
- src/utils.js
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
- tests/utils.spec.js
This PR is the same as https://github.com/react-component/table/pull/211, but address the comments of @yesmeck.
@matthewlein was contractor for us and is no longer on the project and will more than likely not update the other PR.
> Render data- and aria- props

- src/ExpandableTable.js
Fix => https://github.com/ant-design/ant-design/issues/16175
Note: The root cause of not being able to click links on the table cell is because the default behavior is being disabled.
> Fix invalid click when expandRowByClick prop is enabled

- assets/index.less
- src/BodyTable.js
- src/HeadTable.js
- src/utils.js
- tests/__snapshots__/Table.spec.js.snap
close ant-design/ant-design#4637
close ant-design/ant-design#14211
close #285
close #219 
close #304
这里用
```css
.ant-table-header::-webkit-scrollbar {
background-color: transparent;
}
```
的方式去解决 ant-design/ant-design#4637 的问题。但是这样会影响 scrollbar 宽度的计算（导致  https://github.com/ant-design/ant-design/issues/4936 ），所以把这个单独提成 className 应用到滚动条宽度计算的临时元素上。
> fix(Table): Hide header extra scrollbar

- src/HeadTable.js
https://github.com/ant-design/ant-design/issues/17051#issuecomment-501191421
> fix: `overflow: auto auto;` not working in safari

- src/BodyTable.js
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
add `tabIndex` to support scroll by key.
fix: https://github.com/ant-design/ant-design/issues/17643
> fix: Browser not scroll-able by key

- src/ExpandableRow.js
- tests/Table.expandRow.spec.js
Related issue: https://github.com/ant-design/ant-design/issues/17720
antd should also update to use `expandIcon` instead of css icon.
> feat: Not hide icon if `expandIcon` provided

- README.md
- assets/index.less
- examples/ellipsis.js
- package.json
- src/Table.js
- src/TableCell.js
- src/TableHeaderRow.js
- tests/Table.spec.js
- tests/__snapshots__/Table.expandRow.spec.js.snap
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
https://github.com/ant-design/ant-design/pull/17284
> support tableLayout and column.ellipsis

- src/Body/BodyRow.tsx
后台返回的数据都会有children字段，应该判断值，才显示前面那个折叠/显示 图标
> children value should be check

- package.json
- src/Cell/index.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/20734
> fix: Table column render with array

- examples/debug.tsx
- src/Body/BodyRow.tsx
- src/Header/HeaderRow.tsx
- src/hooks/useStickyOffsets.ts
- src/utils/valueUtil.tsx
fix https://github.com/ant-design/ant-design/issues/20744
> fix: Do not blink when columns change with fixed

- src/TableRow.tsx
- tests/Table.fixedColumns.spec.js
using react-dnd to make BodyRow, set some column to fixed. In some case, this will make tableRow render function to return a null object, then saveRef function will call getBoundingRect on a null object which cause crash.
> fix(tableRow): 修复tableRow某些情况下rowRef为null时, saveRef会引发页面crash

- src/Table.tsx
- tests/ExpandRow.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/20743
> fix: Correct the size of resize observer

- src/Body/BodyRow.tsx
- src/Body/index.tsx
- tests/Table.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/20814
> fix: Table row missing `data-row-key`

- src/Body/BodyRow.tsx
- src/Body/index.tsx
- src/Header/Header.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/interface.ts
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/20928
> refactor: Move all measure into table body

- src/Table.tsx
- tests/Internal.spec.js
ref https://github.com/ant-design/ant-design/issues/21154
> feat: Table expanded icon pass internal status

- .travis.yml
- src/Table.tsx
- src/utils/expandUtil.tsx
- tests/ExpandRow.spec.js
fix https://github.com/ant-design/ant-design/issues/21788
> fix: defaultExpandAllRows should work with childrenColumnName

- src/Cell/index.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/21541
> fix: Remove cell memo

- assets/index.less
- examples/fixedColumnsAndHeaderRtl.tsx
- src/Body/BodyRow.tsx
- src/Cell/index.tsx
- src/Header/FixedHeader.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/context/TableContext.tsx
- src/hooks/useColumns.tsx
- src/hooks/useStickyOffsets.ts
- src/utils/fixUtil.ts
- tests/FixedColumn.spec.js
- tests/Table.spec.js
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
Just added some fixes for rtl direction.
Fixed columns in rtl direction will be displayed correctly with these changes.
> Add rtl direction

- src/Header/Header.tsx
- src/hooks/useColumns.tsx
修复当，外围存在一些逻辑操作columus时如reduce, 会对无效的group 识别为group, 导致列头无法显示（均为空group）
动态组装的columus 肯定会声明column 的children,  比如 {
children: xxx ? yyy : nnn
}
但是代码中使用的in 操作符，会识别为column group
> fix: when the children of the table column is falsely still recognized as a column group

- src/Table.tsx
- src/hooks/useStickyOffsets.ts
fix https://github.com/ant-design/ant-design/issues/22262
Hard to measure for the style trigged resize.
> fix: Update memo logic

- src/ColGroup.tsx
- tests/Colgroup.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
resolve https://github.com/ant-design/ant-design/issues/22432
> chore: Not render 0 width col

- .eslintrc.js
- src/Body/BodyRow.tsx
- src/Body/ExpandedRow.tsx
- src/Body/index.tsx
- src/Table.tsx
- src/context/BodyContext.tsx
- tests/FixedColumn.spec.js
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
ref https://github.com/ant-design/ant-design/issues/22557
> refactor: Expandable without fixed column should not sticky

- src/Body/index.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/23297
> fix: Table onRow not refresh Table

- src/Table.tsx
有使用fixedColumns时才执行event.preventDefault等逻辑。
> no need to do event.preventDefault when not use fixedColunms

- assets/index.less
- examples/fixedColumns.tsx
- src/Body/BodyRow.tsx
- src/Body/index.tsx
- src/Footer/Cell.tsx
- src/Footer/Row.tsx
- src/Footer/index.tsx
- src/Table.tsx
- src/context/TableContext.tsx
- src/index.ts
- src/interface.ts
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
`summary` 新增一种数据格式，用于支持固定列的展示：
```tsx
<Table
{...props}
summary={() => (
<tr>
<Table.SummaryCell index={0} colSpan={2}>
Light
</Table.SummaryCell>
<Table.SummaryCell index={2}>Bamboo</Table.SummaryCell>
</tr>
)}
/>
```
preview: https://table-git-fixed.react-component.now.sh/iframe.html?id=rc-table--fixedcolumns
------
原：
```tsx
<Table
{...props}
summary={() => [
[
{ children: 'Light', props: { colSpan: 2 } },
{ children: 'Hidden', props: { colSpan: 0 } },
{ children: 'Bamboo' },
],
]}
/>
```
> feat: Table summary support fixed column

- src/Body/BodyRow.tsx
- src/Table.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/23697
> fix raw type crash

- .eslintrc.js
- src/Body/BodyRow.tsx
- src/Cell/index.tsx
- src/interface.ts
- tests/Table.spec.js
ref: https://github.com/ant-design/ant-design/issues/23763
> feat: Column support `shouldCellUpdate`

- examples/expandIcon.tsx
- src/Table.tsx
- tests/ExpandRow.spec.js
https://github.com/ant-design/ant-design/issues/23894
https://github.com/react-component/table/pull/468
> fix table icon cannot expand when has expandRowByClick

- examples/expandIcon.tsx
- src/Table.tsx
- src/hooks/useColumns.tsx
- tests/ExpandRow.spec.js
close https://github.com/ant-design/ant-design/issues/23894
> fix expandRowByClick

- src/Cell/index.tsx
- src/interface.ts
- tests/Table.spec.js
ref https://github.com/ant-design/ant-design/issues/24946
> feat: shouldCellUpdate return prev value

- src/Body/index.tsx
@afc163 This seem like a typo. But it will slow down antd 4 table render.
Let me show you detail:
In a non-empty table. The `rows` is `[[BodyRow], [BodyRow2] ...]` currently. Every time user insert data into table. Existed rows will recreate even they have same keys. I think most user show table with pagination. So people ignore this for a long time.
This pr fix https://github.com/ant-design/ant-design/issues/25224 , you can try reproduction demo in that issue. There are two gif show the difference between ant3 and ant4.
> fix: remove body row array wrapper

- src/Table.tsx
- tests/Scroll.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
https://github.com/ant-design/ant-design/issues/25124
> Antd #25124 hide horizontal scroll when no need

- src/Header/FixedHeader.tsx
- src/Table.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/25689
> fix: Header flicker

- src/Table.tsx
- tests/ExpandRow.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/25736
> fix: Not render children when invalidate

- assets/index.less
- examples/stickyHeader.tsx
- src/Cell/index.tsx
- src/Header/FixedHeader.tsx
- src/Header/Header.tsx
- src/Table.tsx
- src/context/TableContext.tsx
- src/interface.ts
- src/stickyScrollBar.tsx
- src/utils/fixUtil.ts
- tests/Sticky.spec.js
ref: https://github.com/ant-design/ant-design/pull/25939
> fix: sticky with fixed columns

- src/Header/Header.tsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
Remove falsy value in columns, so that we can do expression in the column arrays. For example:
```
let showId = false
const columns = [
{
title: 'Name',
dataIndex: 'name',
key: 'name'
},
showId && {
title: 'ID',
dataIndex: 'id',
key: 'id'
}
]
```
> [enhance]remove falsy column

- src/Header/FixedHeader.tsx
- tests/FixedHeader.spec.js
- tests/__snapshots__/Table.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/26438
> fix: 0 is a validate width

- src/Body/MeasureCell.tsx
- src/Body/index.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/26438
> fix: Always trigger resize once

- src/Body/MeasureCell.tsx
- src/Table.tsx
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
columns 超过宽度时去掉 scrollX 会导致无数据下被挤到一起的问题。
ref https://github.com/react-component/table/commit/fab74ef6a3b08c4f95cbaddb9078024d8dc3f6cd
> fix: Default provides width even when no data

- src/Header/FixedHeader.tsx
- src/Table.tsx
- src/hooks/useSticky.ts
- tests/FixedHeader.spec.js
- tests/Scroll.spec.js
fix https://github.com/ant-design/ant-design/issues/26766
> fix: header support scroll

- README.md
- assets/index.less
- examples/stickyHeader.tsx
- src/Table.tsx
- src/hooks/useSticky.ts
- src/interface.ts
- src/stickyScrollBar.tsx
- tests/Sticky.spec.js
Resolve https://github.com/react-component/table/issues/528
Ref: https://github.com/ant-design/ant-design/issues/26399
> feat: sticky getContainer

- src/hooks/useFrame.ts
argument to clearTimeout can be number / undefined
frameRef can be State | null，should not be undefined
> fix: useTimeoutLock type fix

- src/hooks/useColumns.tsx
- src/interface.ts
[table的expandable的icon宽度可设置](https://github.com/ant-design/ant-design/issues/28147)
> feat: add columnWidth prop for expandable config

- src/hooks/useStickyOffsets.ts
fix misspelling in src/hooks/useStickyOffsets.ts
> fix misspelling

- src/Body/BodyRow.tsx
- src/Body/index.tsx
- src/ColGroup.tsx
- src/Header/FixedHeader.tsx
- src/Header/Header.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/context/BodyContext.tsx
- src/context/TableContext.tsx
- src/hooks/useColumns.tsx
- src/interface.ts
- src/sugar/ColumnGroup.tsx
- src/utils/expandUtil.tsx
- src/utils/fixUtil.ts
- src/utils/valueUtil.tsx
Our data types are immutable and we can't use rc-table unless we use `.slice()` to clone data and convert it to mutable array. 
```tsx
<Table data={myImmutableArray.slice()} />
```
But the implementation of rc-table does not rely on mutable array, it should be immutable.
So I change the props types of rc-table to immutable array such that I can use
```tsx
<Table data={myImmutableArray} />
```
related issue: https://github.com/NG-ZORRO/ng-zorro-antd/pull/6156#event-4237225595
> feat: use ReadonlyArray in props

- docs/examples/fixedColumnsAndHeader.tsx
- src/Header/FixedHeader.tsx
- src/Table.tsx
- tests/FixedColumn.spec.js
- tests/__snapshots__/FixedColumn.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/29720
fix https://github.com/ant-design/ant-design/issues/29395
> fix: Let width go when scroll do not have the data

- src/Header/FixedHeader.tsx
- src/Table.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
> fix: table header broken when scroll do not have the data(#594)

- docs/examples/expandedRowRender.tsx
- src/Table.tsx
- src/hooks/useColumns.tsx
- src/interface.ts
close https://github.com/ant-design/ant-design/issues/29924
---
`expandable` 增加了 `fixed`
- 当设置 true 或 `left` 且 expandIconColumnIndex 没设置或为 0 时，即在最左边，开启 expandable icon fixed left
- 当设置 true 或 `right` 且 expandIconColumnIndex 设置 最大列数时，即在最右边，开启 expandable icon fixed right
> feat: add expandable fixed

- src/Table.tsx
Performance optimization: when only height is changed, don't trigger re-render.
> Only trigger full table resize if width changes.

- package.json
- src/Table.tsx
- tests/__mocks__/rc-util/lib/getScrollBarSize.ts
fix https://github.com/ant-design/ant-design/issues/30358
> fix: Customize scroll bar size of table

- src/ColGroup.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
Seems `min-width` never work as expect. Just remove it.
ref https://github.com/react-component/table/blame/35f7831f5d9f9e5569f509483493d88bc044f450/src/ColGroup.js#L33
resolve https://github.com/ant-design/ant-design/issues/30755
> fix: rm useless `min-width`

- src/Cell/index.tsx
- tests/Cell.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/30715
> fix: shouldCellUpdate should not ignore className

- src/Body/BodyRow.tsx
- tests/Table.spec.js
fix ant-design/ant-design#32892
> fix: throw error when clicking row with no set onClick in onRow

- docs/demo/fixedColumns-resize.md
- docs/examples/fixedColumns-resize.tsx
- src/Body/BodyRow.tsx
- src/Body/ExpandedRow.tsx
- src/Body/index.tsx
- src/Table.tsx
- src/context/BodyContext.tsx
- src/context/ExpandedRowContext.tsx
**问题描述**：设置 scroll.x，resize 或者切换侧边栏时，卡顿明显。Ref: ant-design/ant-design#27775
**解决方式**：将只在 `ExpandedRow` 中用到的 `fixColumn/fixHeader/componentWidth` 单独提取到一个 Context 中
**优化结果**：固定栏折叠时更改 table 宽度，所需用时 **510.4±13.7ms ➜ 104.1±5ms**
**具体分析**：https://github.com/react-component/table/pull/701
> perf: extract expanded row context

- docs/examples/subTable.tsx
- src/Body/index.tsx
- src/hooks/useFlattenRecords.ts
- tests/Table.spec.js
fix ant-design/ant-design#33056
例子subTree, render索引正常了
> fix: wrong index in tree table

- package.json
- src/Body/MeasureCell.tsx
- src/Body/MeasureRow.tsx
- src/Body/index.tsx
- tests/FixedColumn-IE.spec.js
- tests/FixedColumn.spec.js
- tests/FixedHeader.spec.js
**问题描述**：设置 scroll.x，resize 或者切换侧边栏时，卡顿明显。Ref: ant-design/ant-design#27775
**解决方式**：单个 `ResizeObserver` 实例 `observe` 所有列，支持在一个 Task 周期批量处理 Resize 引发的 Update
**优化结果**：固定栏平铺-折叠切换，所需用时 **6646.2ms ➜ 1080.8 ms**
**具体分析**：https://github.com/react-component/table/pull/701#discussion_r752994243
> perf: observe columns with one ResizeObserver instance

- src/Footer/Cell.tsx
Warning started appearing on `Table.Summary.Cell` on antd v4.18.0 due to 75ee0064e54a4b321569450
close https://github.com/react-component/table/issues/722
close #724
close ant-design/ant-design#33488
> fix: SummaryCell triggering `onCell` warning

- src/stickyScrollBar.tsx
经调查，出现在离开页面，组件卸载且页面出现滚动重置时，getOffset 参数会为 null
> fix: read property getBoundingClientRect of null when unmount

- src/Body/BodyRow.tsx
- src/Body/ExpandedRow.tsx
- src/Body/index.tsx
- src/Table.tsx
- src/context/ExpandedRowContext.tsx
修复表格空状态时 emptynode 未固定显示的问题
7.20.2之前，这里的传值是模糊的
7.20.2之后，在 https://github.com/react-component/table/blob/b973d405b9e2552e41c3fccc992da1362b8622d4/src/Body/ExpandedRow.tsx#L33 改成了始终使用 `ExpandedRowContext` 中的 `fixColumn`，空状态时 `fixColumn` 为 `false`，就造成了显示上的问题
> fix: table emptynode fixed display

- src/Body/BodyRow.tsx
- src/Body/index.tsx
- src/Cell/index.tsx
- tests/Table.spec.js
出现hover错误的原因是 子cell分配的index出现问题，分配的index应该是对于整个flattenData，而在前面的错误中分配index为每个子数组中相应数据的index
仅仅修改将renderIndex取消传值，测试用例会发生错误。
所以增加一个renderIndex的prop传值，将render传入的index用renderIndex替代，其他的维持正确的index。
> fix: antd #33453 fix the table tree hover error

- src/Footer/Cell.tsx
- src/Footer/Summary.tsx
- src/Footer/index.tsx
fixes: https://github.com/react-component/table/issues/737
> fix: footer circular dependency

- src/Body/index.tsx
- src/Cell/index.tsx
- src/context/PerfContext.tsx
- tests/Hover.spec.tsx
ref https://juejin.cn/post/7063332320339099678?utm_source=ZHShareTargetIDMore&utm_medium=social&utm_oi=1001194210325868544
> perf: Cell not render if no additional perf cost

- src/Footer/Cell.tsx
- src/Footer/Summary.tsx
- src/Footer/SummaryContext.tsx
- src/Footer/index.tsx
The last circular dependency fix merely changed where the circular dependency occurred, as Footer/Summar.tsx imports from Footer/Cell.tsx and vice versa. So I Isolated the `SummaryContext` constant and the type it uses to its own file to break that circular import. 
Verified the fix using madge https://www.npmjs.com/package/madge
> fix: Summary Context Circular Dependency

- src/Body/index.tsx
- src/Cell/index.tsx
- tests/FixedColumn.spec.js
- tests/__snapshots__/FixedColumn.spec.js.snap
close https://github.com/ant-design/ant-design/issues/34208
> fix: ellipsis cell title lost when is last fixed column

- src/Table.tsx
- tests/ExpandRow.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
采用了Junlin-Tommy在[原PR](https://github.com/react-component/table/pull/764)提出的[修改方案](https://github.com/react-component/table/pull/764#discussion_r828693506)，减少对代码逻辑的改动。补充了测试用例。
修复了[issue#755](https://github.com/react-component/table/issues/755)第一点提及的问题。
antd的官方文档中并未提及expandable.fixed 和 scroll 两属性需要同时设置，因此将scroll属性置空不应导致整个table crash。采用了默认的auto方式设置水平方向的scroll。
> fix: table crashes if expandable set without scroll

- docs/examples/column-resize.tsx
- src/Body/MeasureRow.tsx
由于延迟更新column宽度，导致表头表body宽度更新不同步
https://github.com/ant-design/ant-design/issues/33545
移除2帧的延迟
> fix: header column resize delay

- src/hooks/useColumns.tsx
- tests/FixedColumn.spec.js
fix: https://github.com/ant-design/ant-design/issues/35365
> fix: receive an error warning when the direction is rtl

- docs/examples/virtual-list-grid.tsx
当修改table的dataSource时，拿不到正确的scrollBodyRef.scrollLeft而导致的header的scrollLeft不正确
> fix(example/virtual-list-grid): 完善virtual-list-grid的demo

- README.md
When we pass `rowKey` with a function, it will actually invoked as `rowKey(record, index)`,  where the second parameter is the index of dataSource. We may find evidence in the following code:
```ts
// src/Body/index.tsx:68
let rows: React.ReactNode;
if (data.length) {
rows = flattenData.map((item, idx) => {
const { record, indent, index: renderIndex } = item;
const key = getRowKey(record, idx);
// ...
}
}
```
This is also confirmed in the type definition:
```ts
// src/interface.ts:97
export type GetRowKey<RecordType> = (record: RecordType, index?: number) => Key;
```
However, the information about the second parameter is not explicitly mentioned in README.md. In addition, there is no information provided about second parameter in the document of `Table` component of Ant Design, which …
> docs: better rowKey type

- src/Table.tsx
- tests/Table.spec.js
- tests/__mocks__/rc-util/lib/getScrollBarSize.ts
- tests/__snapshots__/Table.spec.js.snap
ref: https://github.com/ant-design/ant-design/issues/35665
在不一定能保证用户传入的`components`为`Element Type`的情况下
退而求其次，获取其容器组件的scrollBarSize
> fix: no scrollbar size issue

- src/Body/ExpandedRow.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
ref https://github.com/ant-design/ant-design/issues/35476
> fix: render empty node after get container size

- src/Table.tsx
- tests/FixedColumn.spec.js
When you:
- have rendered a table that fits on your screen
- you resize the view so that the scrollbar appears and the shadows on the table
- you go back to the original size of the screen
**What happens**
The shadows are still there
**What should happen**
The shadows are gone since there's no longer a scrollbar, nor a need to scroll
This is because the code is jumping out of the function when the scrollwidth and clientwidth are the same, but it doesn't reset the pingedLeft and pingedRight values.
close https://github.com/react-component/table/pull/837
close https://github.com/react-component/table/pull/834
close https://github.com/ant-design/ant-design/issues/35817
> Fix shadows still shown after resize to fullscreen

- package.json
Dear RC-team
It seems that commit https://github.com/react-component/table/commit/4e64b556259948fa01bd1c1329a3a32c4dcbfb0d introduced a dependency to rc-util's `useEvent` hook, which has been introduced with `rc-util@5.22.0`. On the other hand, this package still lists `rc-util: ^5.14.0` in its package dependencies. This leads to bundling errors such as:
```
ERROR in ../../node_modules/rc-table/es/ContextSelector/index.js 4:0-49
Module not found: Error: Can't resolve 'rc-util/es/hooks/useEvent' in '/<project-dir>/node_modules/rc-table/es/ContextSelector'
```
I therefore bump the rc-util dependency to the current version `5.22.5`.
> Bump outdated rc-util dependency

- docs/demo/caption.md
- docs/examples/caption.tsx
- src/Table.tsx
- src/interface.ts
- src/utils/legacyUtil.ts
- tests/Table.spec.js
Captions provide information that can help users find, navigate, and understand tables. While they are not required in every case to meet WCAG, captions are fairly straightforward ways to provide such information that is often needed.
This PR adds an optional `caption` prop to the Table component to allow users to define a caption using a string or a ReactNode.
> Adds ability to define a caption

- package.json
- src/Table.tsx
- tests/Scroll.spec.js
fix https://github.com/ant-design/ant-design/issues/37179
当动态新增 `columns` 时，调用 `forceScroll` 方法，设置 `scrollLeft`，并不起作用，发现此时的 `scrollLeft` 为 0，
[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollLeft)
> 如果元素不能滚动（比如：元素没有溢出），那么 `scrollLeft` 的值是 0。
如果给 `scrollLeft` 设置的值小于 0，那么 `scrollLeft` 的值将变为 0。
如果给 `scrollLeft` 设置的值大于元素内容最大宽度，那么 `scrollLeft` 的值将被设为元素最大宽度。
此时我打印了 `scrollWidth`，发现 `scrollWidth` 与预期不同，正常 `scrollWidth` 应该为 1800(此值为上方bug链接中的案例)， 此时为 358， 与`offsetWidth`，猜测符合MDN中说的第一条规则，**如果元素不能滚动（比如：元素没有溢出），那么scrollLeft 的值是 0**。
解决办法：
我能想到的就是将 `scrollLeft` 设置推迟到 dom 更新后执行，不知道有没有更好的办法😮‍💨
> fix: 🐛 forceScroll error

- docs/demo/aria.md
- docs/examples/aria.tsx
- src/Table.tsx
- tests/Table.spec.js
aria- attributes should be applied to the `<table>` element.  Instead, they are applied to the great grandparent of the `<table>` element where they serve no purpose. eg:
This PR moves them to the correct element. As a result, screen readers will correctly announce the table.
This PR does NOT change where the data- props are added (still on the great grandparent of the `<table>` element).
ref: UIEN-973
> Corrects the element that aria- props are applied to

- package.json
- src/Cell/index.tsx
- src/Table.tsx
- src/utils/valueUtil.tsx
修复 https://github.com/ant-design/ant-design/issues/36988 之前发现有些代码可以提前重构，PR 分片降低 CR 成本。
> refactor: Part refactor

- .gitignore
- package.json
- src/Table.tsx
- src/index.ts
> feat: export genTable

- src/Footer/Cell.tsx
- src/Footer/SummaryContext.tsx
- src/Footer/index.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/hooks/useFixedInfo.ts
- src/utils/fixUtil.ts
- tests/FixedHeader.spec.js
close https://github.com/ant-design/ant-design/issues/39880
> fix: solve table display unexpected when column fixed

- tests/FixedColumn.spec.js
- tests/FixedHeader.spec.js
- tests/Sticky.spec.js
- tests/utils.js
解决运行测试命令时除预期的`warning`输出之外，其他的`console.error`输出
- https://github.com/ant-design/ant-design/issues/40236
> chore: optimize test case

- src/hooks/useColumns.tsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
[[中文版模板 / Chinese template](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE/pr_cn.md)]
fix [#40568](https://github.com/ant-design/ant-design/issues/40568)
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     Make Table's columns support conditional rendering      |
| 🇨🇳 Chinese |    让 Table 的 column 支持条件判断渲染     |
⚠️ Please check all items below before requesting a reviewing. ⚠️
> perf: make column support jsx conditions (#40568)

- package.json
- src/Cell/index.tsx
- tests/ColSpan.spec.js
minor version since this may affect some usage case:
ref https://github.com/ant-design/ant-design/issues/40753
> feat: re-order that onHeadCell props has higher proirity

- src/utils/fixUtil.ts
Closes https://github.com/ant-design/ant-design/issues/41070
There is a problem in ant design's Table component in **rtl** direction when using fixed summary.
I tested the changes in **sticky-header-and-summary** example and it was okay.
> 🐞 FIX: swap columns for rtl direction

- src/Table.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/41150
Issue: Error message logged on the console when columns is empty []. This issue occurs in the custom body component: 
```
<Table
{...props}
components={{
body: renderSomethinig,
}}
/>
```
After looking into it, I find that there's no major issue when columns is empty []. So, I just added a conditional  check to only log an error if columns.length > 0.
| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   fix error message being logged in the custom body component when columns is empty []         |
| 🇨🇳 Chinese |  修复自定义 body component, columns[] 為空時 错误报错错误报
⚠️ Please check all items below before requesting a reviewing. ⚠️
> fix: table warning message when columns=[]

- src/Table.tsx
did two things:
- improve auto completion, by using the same technique that ant-design is using: [LiteralUnion](https://github.com/ant-design/ant-design/blob/f53618ddaa753c2614f777a7883d1b342bf3bdd8/components/_util/type.ts#L2)
- remove redundant type annotation: the union type `React.ReactNode` already has `string`
> feat(type): improve autocompletion for `rowKey`

- src/Table.tsx
- src/constant.ts
- src/hooks/useExpand.ts
- tests/Internal.spec.js
- tests/Table.spec.js
> fix: fix circular-depdcy

- src/interface.ts
**AlignType** should match **csstype** package **Property.TextAlign**
> fix: AlignType missing values

- src/hooks/useFlattenRecords.ts
> use array concatenation instead of push in useFlattenRecords hook

- README.md
Currently, the docs page at https://table.react-component.now.sh cannot be shown and throwing this error:
This is due to the `<HTMLElement>` that was added in the `README.md` at commit https://github.com/react-component/table/pull/985/commits/c43523efb86d3911b915ebdcec916934561401be has no escape character (`/`), therefore being unintentionally compiled as a real HTML element.
This PR fixes #992 by adding an escape character so that https://table.react-component.now.sh is back online again.
> fix: cannot render docs page

- assets/index.less
Missing styling added for caption. 
closed  [#999]
> fix: Missing caption styling

- src/interface.ts
close https://github.com/ant-design/ant-design/issues/43036
close https://github.com/ant-design/ant-design/pull/43172
`caption` 是 table 内嵌元素，和 `title` 是不等价的。这个不能直接 deprecated：
> chore: rm title deprecated mark

- src/Table.tsx
- tests/Table.spec.jsx
**问题demo：**
https://codesandbox.io/s/spring-dream-qqywty?file=/App.tsx
> 修复当自定义表格体功能（components.body）和表头分组功能（column.children）同时使用时，会出现表头和表体不对齐的问题

- src/Body/ExpandedRow.tsx
When a table has 'scrollX' prop is initialized , the height of the table body collapses to zero. This issue leads to shaking when two tables are switched. The root cause is the presence of empty text in ExpandedRow. To address this, introduce a conditional check for horizonScroll to prevent this unintended behavior.
issue: https://github.com/ant-design/ant-design/issues/44281
> fix: rerender table trigger table-body collapses

- src/VirtualTable/BodyLine.tsx
- src/VirtualTable/VirtualCell.tsx
- tests/Virtual.spec.tsx
fix https://github.com/ant-design/ant-design/issues/44783
> fix: VirtualTable missing `renderIndex` param for `column.render`

- docs/examples/virtual.tsx
- package.json
- src/VirtualTable/BodyGrid.tsx
resolve https://github.com/ant-design/ant-design/issues/44748
`rc-virtual-list` 原来已经做过这个功能了，和过去的自己击个掌 🙌
> fix: VirtualTable should auto collapse if items is less than scrollY

- docs/examples/virtual.tsx
- src/Table.tsx
- src/VirtualTable/index.tsx
- src/hooks/useColumns/index.tsx
- src/hooks/useColumns/useWidthColumns.tsx
- tests/Virtual.spec.tsx
ref https://github.com/ant-design/ant-design/issues/44785
> fix: auto spread width when table size is large than columns

- src/Body/BodyRow.tsx
- tests/ExpandRow.spec.jsx
更标准的解法应该是 `useState` 在关闭时一起做 state 更新，但是这样会让渲染逻辑变得过于复杂。只为了少一次渲染会变得缺少性价比。
close https://github.com/ant-design/ant-design/issues/44890
> enhance: Rm duplicated re-render of expanded row

- src/VirtualTable/index.tsx
- src/hooks/useColumns/useWidthColumns.tsx
- tests/Virtual.spec.tsx
- tsconfig.json
fix https://github.com/ant-design/ant-design/issues/44939
> fix: scroll.x not working when no fixed column exists

- package.json
- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/context.ts
- src/VirtualTable/index.tsx
- tests/Virtual.spec.tsx
fix https://github.com/ant-design/ant-design/issues/45014
fix https://github.com/ant-design/ant-design/issues/44869
> fix: support sticky when virtual

- src/Table.tsx
- tests/Node.spec.jsx
> fix: run in node before not ready

- docs/demo/virtual-columns.md
- docs/examples/fixedColumns.tsx
- docs/examples/virtual-columns.tsx
- src/hooks/useColumns/useWidthColumns.tsx
- src/index.ts
- tests/Virtual.spec.tsx
fix https://github.com/ant-design/ant-design/issues/45281
> fix: Width exceed logic

- src/Cell/index.tsx
自定义 components body 的 cell 时，用 React.memo 可以自定义比较 style 等一些引用类型，但是这两个函数无法自定义 memo。
> perf: memo onMouseEnter、onMouseLeave

- docs/examples/virtual.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/BodyLine.tsx
- src/VirtualTable/VirtualCell.tsx
- src/VirtualTable/context.ts
- src/VirtualTable/index.tsx
- tests/Virtual.spec.tsx
close https://github.com/ant-design/ant-design/pull/47090
close https://github.com/ant-design/ant-design/issues/47073
ref: https://github.com/ant-design/ant-design/issues/46866 
ref: https://github.com/ant-design/ant-design/issues/46295
Notice: components.body.wrapper 的自定义组件需要用 React.forwardRef 包裹并传递 ref，因为 rc-virtual-list 有用到做计算
> feat: support virtual components.body

- docs/demo/expandedRowClassName.md
- docs/examples/expandedRowClassName.module.less
- docs/examples/expandedRowClassName.tsx
- src/Body/BodyRow.tsx
- tests/ExpandRow.spec.jsx
原代码中 expandedRowClassName 必须依赖 expandedRowRender 才能生效~
修改后, 默认的扩展列渲染也可以生效了.
这个 bug  好几年了~~
> expandedRowRender 不生效

- .github/workflows/main.yml
- assets/index.less
- docs/examples/fixedColumns.tsx
- package.json
- src/Table.tsx
- src/hooks/useColumns/index.tsx
- src/hooks/useStickyOffsets.ts
- src/index.ts
- tests/FixedColumn.spec.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tests/setup.ts
- tsconfig.json
> feat: Cross fixed column support

- src/Header/Header.tsx
- src/Header/HeaderRow.tsx
- tests/FixedColumn.spec.tsx
- tests/Table.spec.jsx
- tests/__snapshots__/ExpandRow.spec.jsx.snap
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tests/__snapshots__/Table.spec.jsx.snap
> fix: change tag td => th

- src/Table.tsx
- src/stickyScrollBar.tsx
fix https://github.com/ant-design/ant-design/issues/47331
fix https://github.com/ant-design/ant-design/issues/33762
结论：最好的方式是用 ResizeObserver 监听 table body 高度（会耗一些性能），但是基本场景监听 data 变化去检测也够用了，有人提问题的话之后再把 useEffect 的依赖项去掉
https://github.com/react-component/table/assets/47104575/edb54c74-49ad-4837-b46a-7dffb1041164
> fix: should check sticky scroll bar visible when table height changed

- docs/demo/shadow.md
- docs/examples/shadow.tsx
- src/Footer/Cell.tsx
- src/Footer/SummaryContext.tsx
- src/Footer/index.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/hooks/useFixedInfo.ts
- src/utils/fixUtil.ts
- tests/FixedColumn.spec.tsx
- tests/__mocks__/shadowTest.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tsconfig.json
- vitest.config.ts
fix https://github.com/ant-design/ant-design/issues/47374
> fix: solve fixed column's shadow display unexpected issue

- docs/examples/virtual.tsx
- src/VirtualTable/BodyGrid.tsx
- tests/Virtual.spec.tsx
**background**: https://github.com/ant-design/ant-design/issues/46177 需要修改滚动条样式，但是 rc-table 的虚拟列表没有将 `prefoxCls` 透下去。
> fix: virtual list prefixCls not working

- src/interface.ts
ref: https://github.com/react-component/table/pull/1091
> chore: adjust dataIndex def

- src/interface.ts
> fix: dataindex allow array

- src/Table.tsx
- src/stickyScrollBar.tsx
ref https://github.com/react-component/table/pull/1078
这里已经有 ResizeObserver 了
https://github.com/react-component/table/pull/1099/files#diff-5136c989c296c26b5ee1d8662fbfd58d269e40e67a6f02b35f55442ab4835c3bL784
> fix: use Observer to check sticky bar

- src/FixedHolder/index.tsx
Calling `preventDefault` in onWheel is possibility. `passive` cannot be set to true. Set it to false to suppress warnings.
close #996
> chore: event passive false

- src/Body/ExpandedRow.tsx
- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/index.tsx
- tests/Virtual.spec.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
virtual table empty 时，body 使用正常表格渲染。
另外 empty 时，scrollY 应该为 auto，也更美观。
fix https://github.com/ant-design/ant-design/issues/48991
> fix: virtual table should be able to scroll when empty

- docs/examples/virtual.tsx
- package.json
- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/index.tsx
- tests/Virtual.spec.tsx
- tests/__snapshots__/ExpandRow.spec.jsx.snap
- tests/__snapshots__/FixedColumn.spec.tsx.snap
fix https://github.com/ant-design/ant-design/issues/48959
> fix: right shadow should display correctly in virtual when mount

- src/stickyScrollBar.tsx
- tests/Sticky.spec.jsx
一开始是不应该显示的，否则一开始可能会出现双滚动条，然后 check 后再消失，会闪动一下，应改成默认不展示，执行 check 后如果判断需要展示再展示出来。
（我自己的项目中出现了这种问题，手动修改 node_modules 中 rc-table 源码后可修复）
> fix: change sticky scroll bar default state

- README.md
- src/ColGroup.tsx
- src/interface.ts
- tests/Colgroup.spec.jsx
只在 `tableLayout='auto'` 时有效，所以根据以下代码实际上大多数情况 `minWidth` 都无效。
> feat: column minWidth

- .husky/pre-commit
- src/Cell/index.tsx
- tests/__snapshots__/ExpandRow.spec.jsx.snap
- tests/__snapshots__/FixedColumn.spec.jsx.snap
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tests/__snapshots__/Summary.spec.tsx.snap
- tests/__snapshots__/Table.spec.jsx.snap
Reverts react-component/table#1110
Reason to revert: https://github.com/ant-design/ant-design/issues/48477#issuecomment-2291546301
> Revert "fix(table): When ellipsis is undefined, title is undefined"

- docs/examples/scrollY.tsx
- src/Table.tsx
- tests/Scroll.spec.jsx
> fix:doesn't scroll when use scrollTo with `top` zero

- .github/workflows/main.yml
- src/stickyScrollBar.tsx
fix https://github.com/ant-design/ant-design/issues/53085
> fix: virtual scroll logic

- src/VirtualTable/BodyGrid.tsx
- tests/Virtual.spec.tsx
background: https://github.com/ant-design/ant-design/issues/54734
antd 侧在 https://github.com/ant-design/ant-design/blob/ddd525c7891fe94123e6c5b160f80ed630e8de26/components/table/InternalTable.tsx#L279-L281 使用了元素进行滑动操作。 [scrollTo](https://github.com/ant-design/ant-design/blob/ddd525c7891fe94123e6c5b160f80ed630e8de26/components/_util/scrollTo.ts) 源码可以知道。 如果传递的容器不是一个 html 最终会通过设置 scrollTop 来实现滑动。
普通表格中， ref 转发出去的是一个真实的 dom 。所以可以通过 scrollTop 方法进行滑动。
而在虚拟表中， [转发出去的 ref 是一个对象](https://github.com/react-component/table/blob/6c7dee3b88ec1fce680d6d2bd21289f3b46a4313/src/VirtualTable/BodyGrid.tsx#L77-L97)
所以我们需要像 `scrollLeft` 一样，代理一个 `scrollTop` 来解决无法滑动的问题
> fix: Adjust the top height of the proxy to solve the sliding issue

- docs/examples/stickyHeader.tsx
- package.json
- src/FixedHolder/index.tsx
- src/Table.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tests/__snapshots__/Table.spec.jsx.snap
https://github.com/ant-design/ant-design/issues/31494
> fix: Table header layout when data is empty

- src/FixedHolder/index.tsx
解决第一帧对不齐的问题，如果列宽度未计算出来时，直接使用自带的 bodyColGroup。cc @crazyair
> fix: column header not align before column width being calculated

- src/VirtualTable/BodyGrid.tsx
Cherry-pick #1334 for `antd@5.x`
> fix: Table columns minWidth props no work when virtualized (for 5.x)

- assets/index.less
- docs/examples/scrollY.tsx
- docs/examples/stickyHeader.tsx
- src/ColGroup.tsx
- src/FixedHolder/index.tsx
- src/Table.tsx
- tests/__snapshots__/ExpandRow.spec.jsx.snap
- tests/__snapshots__/FixedColumn.spec.tsx.snap
- tests/__snapshots__/Table.spec.jsx.snap
close https://github.com/ant-design/ant-design/issues/54894
>  fix: Table column align issue when scroll.x is true

- src/FixedHolder/index.tsx
- tests/FixedHeader.spec.jsx
https://github.com/ant-design/ant-design/issues/42511
https://github.com/ant-design/ant-design/issues/42544
>  fix: resolve table header blank display issue

- src/Body/MeasureCell.tsx
- src/Body/MeasureRow.tsx
https://github.com/ant-design/ant-design/issues/55039
> fix: Table MeasureRow bug when children have refs
