react-component/table

- README.md
- examples/key.js
- src/Table.jsx
> feat: add key field support

- README.md
- assets/index.less
- examples/fixedColumns.js
- examples/scrollX.js
- examples/scrollXY.js
- examples/scrollY.js
- package.json
- src/Table.jsx
- src/TableRow.jsx
> Feat fixed columns

- src/Table.jsx
Here is a demo for reproducing bug (using Antd): http://codepen.io/wxt2005/pen/EKpLVL?editors=0010
> Fix row with key 0 could not be expanded

- examples/nested.js
- package.json
- src/TableRow.jsx
Adds support for accessing nested data structure with the `dataIndex` prop.
Fixes #46
> Nested data access

- README.md
- src/Table.jsx
- src/TableRow.jsx
ref: https://github.com/ant-design/ant-design/issues/2058
> feat: `rowKey` could be a string

- assets/index.less
- examples/fixedColumns-auto-height.js
- src/Table.jsx
- src/TableRow.jsx
https://github.com/ant-design/ant-design/issues/2106
> auto match height between body table and fixed columns table

- package.json
- src/Table.jsx
> Mobile scroll

- assets/index.less
- examples/no-data.js
- src/Table.jsx
目前antd实现emptyText的方式比较别扭，且有些问题，比如 
https://github.com/ant-design/ant-design/issues/2812
> add emptyText 

- src/Table.jsx
😢 之前写错了，赋值要写在后面，不然比较的时候两次 scrollLeft 永远都是相等的。
> Remember lastScrollLeft later

- README.md
- examples/rowAndCellClick.js
- src/TableCell.jsx
close ant-design/ant-design#3774
> Add column.onCellClick

- src/Table.jsx
- src/utils.js
- tests/Table.spec.js
https://github.com/ant-design/ant-design/issues/4868
> Reduce table nested level

- src/BodyTable.js
- src/HeadTable.js
- src/utils.js
measureScrollbar方法，支持传type参数（width或height）
> measureScrollbar方法，支持传type参数（width或height）

- src/BodyTable.js
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
[https://github.com/ant-design/ant-design/issues/9937](https://github.com/ant-design/ant-design/issues/10392)
> Fixes errors Fixed column and scroll x smaller than view width

- assets/index.less
- package.json
- src/BaseTable.js
- tests/__snapshots__/Table.expandRow.spec.js.snap
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
close ant-design/ant-design#10828
master ci broken
> Hide all fixed columns in body table

- src/Table.js
https://github.com/react-component/table/issues/223
> hidden element can't get getBoundingClientRect().height

- README.md
- examples/rowAndCellClick.js
- src/TableCell.js
> onCell add row index

- src/utils.js
remove excess `else if` in `utils.measureScrollbar`
> remove the code where the grammar is not strict in measureScrollbar

- src/TableHeaderRow.js
- src/TableRow.js
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/15851
> Pass events if `onRow` provides

- src/BodyTable.js
- src/ExpandableTable.js
- src/TableRow.js
- tests/Table.expandRow.spec.js
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
Fix some spelling errors
**Suggestions:**
Install [Code Spell Checker](https://marketplace.visualstudio.com/itemdetails?itemName=streetsidesoftware.code-spell-checker) plugin or open spelling inspections in Jetbrains.
> fix some spelling errors

- src/Table.tsx
antd using ref inner node as popup node which will be reset before each dom render.
ref: https://github.com/ant-design/ant-design/issues/19274
> fix: save function use static

- examples/virtual-list-grid.tsx
- examples/virtual-list.less
- examples/virtual-list.tsx
- package.json
- src/Table.tsx
- src/interface.ts
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
> feat: Add API for customize body list content

- src/TableHeaderRow.tsx
- tests/__snapshots__/Table.expandRow.spec.js.snap
- tests/__snapshots__/Table.fixedColumns.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
https://github.com/ant-design/ant-design/issues/20030
> Add last header cell class

- src/TableHeader.tsx
- src/TableHeaderRow.tsx
- src/interface.ts
- tests/__snapshots__/Table.spec.js.snap
https://github.com/ant-design/ant-design/issues/20030
> fix last header cell className

- src/Header/FixedHeader.tsx
- tests/__snapshots__/Table.spec.js.snap
close https://github.com/ant-design/ant-design/issues/20714
> fix: Hide Header tmp when column data not ready

- package.json
- src/Body/BodyRow.tsx
- src/Header/HeaderRow.tsx
- src/Table.tsx
- src/context/ResizeContext.tsx
- src/utils/valueUtil.tsx
- tests/FixedHeader.spec.js
fix https://github.com/ant-design/ant-design/issues/20995
> fix: Reset order column should sync the column width with fixed header

- assets/index.less
- src/Table.tsx
- tests/__snapshots__/FixedColumn.spec.js.snap
- tests/__snapshots__/Table.spec.js.snap
Fixes https://github.com/ant-design/ant-design/issues/20934
> fix: display scrollBar

- src/Table.tsx
- tests/Scroll.spec.js
- tests/__snapshots__/ExpandRow.spec.js.snap
- tests/__snapshots__/FixedColumn.spec.js.snap
- https://github.com/ant-design/ant-design/issues/21879
- https://github.com/ant-design/ant-design/pull/20705
- https://github.com/ant-design/ant-design/issues/21596
> Tweak Table scroll overflow

- examples/scrollX.tsx
- package.json
- src/Table.tsx
resolve https://github.com/ant-design/ant-design/issues/22000
> chore: Add more memo to optimize scroll render perf

- src/hooks/useFrame.ts
It's same for current test case. Mock timeout test is hard to reproduce.
fix https://github.com/ant-design/ant-design/issues/22232
> fix: Table fixed header tweak when resize

- src/Header/Header.tsx
- src/hooks/useColumns.tsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
close ant-design/ant-design#22804
> fix: Fix column children undefined

- src/Body/BodyRow.tsx
- tests/__snapshots__/ExpandRow.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/23011
> fix data-row-key

- examples/expandIcon.tsx
- src/Table.tsx
- tests/ExpandRow.spec.js
close https://github.com/ant-design/ant-design/issues/23894
> fix: cannot expand when using expandIcon and expandRowByClick

- package.json
> Add type path.

- package.json
- src/Body/index.tsx
- tests/FixedColumn.spec.js
fix https://github.com/ant-design/ant-design/issues/24316
> fix: Measure cell should keep in touch

- src/hooks/useColumns.tsx
- tests/ExpandRow.spec.js
close https://github.com/ant-design/ant-design/issues/24129
close https://github.com/ant-design/ant-design/issues/25386
> fix: expandIconColumnIndex=-1 not working

- .prettierrc
- assets/index.less
- examples/stickyHeader.tsx
- package.json
- src/Header/FixedHeader.tsx
- src/Table.tsx
- src/hooks/useSticky.ts
- src/interface.ts
- src/stickyScrollBar.tsx
- tests/Sticky.spec.js
Ref: https://github.com/ant-design/ant-design/issues/24131
> feat: sticky header and scroll

- src/stickyScrollBar.tsx
- tests/Sticky.spec.js
Ref: https://github.com/ant-design/ant-design/pull/25939#issuecomment-670348248
> fix: resize need

- examples/scrollXY.tsx
- src/Header/FixedHeader.tsx
- src/Table.tsx
- tests/FixedHeader.spec.js
- tests/__snapshots__/FixedColumn.spec.js.snap
fix https://github.com/ant-design/ant-design/issues/26108
> fix: Table should show header when no data

- examples/scrollXY.tsx
- package.json
- src/Table.tsx
- tests/FixedColumn.spec.js
- tests/FixedHeader.spec.js
fix https://github.com/ant-design/ant-design/issues/27049
> fix: Do not record column change when table is invisible

- package.json
- src/Table.tsx
- src/hooks/useFrame.ts
- src/stickyScrollBar.tsx
- tests/FixedColumn.spec.js
- tests/FixedHeader.spec.js
- tests/Sticky.spec.js
- tests/setup.js
resolve https://github.com/ant-design/ant-design/issues/24332
> refactor: Fixed Header no blink

- src/Footer/Cell.tsx
- tests/Table.spec.js
- tests/__snapshots__/Table.spec.js.snap
[#26866](https://github.com/ant-design/ant-design/issues/26866)
> feat: add align prop for Summary.Cell

- src/Table.tsx
Reverts react-component/table#548
> Revert "fix ant-design/ant-design#27359"

- src/interface.ts
/fix: https://github.com/ant-design/ant-design/issues/27685
> fix: expandable API should not be deprecated

- src/Table.tsx
close https://github.com/ant-design/ant-design/issues/27931
> fix: ping left right in rtl

- src/Table.tsx
Resolve https://github.com/ant-design/ant-design/issues/28323
> fix: resolve no date header width when sticky

- docs/examples/childrenIndent.tsx
- docs/examples/expandedRowRender.tsx
- src/Body/BodyRow.tsx
- src/Cell/index.tsx
- tests/Table.spec.js
resolve https://github.com/ant-design/ant-design/issues/30485
> fix: shouldCellUpdate should not block expandable logic

- src/Cell/index.tsx
This PR fixes https://github.com/ant-design/ant-design/issues/30863.
> fix: fix header content not rendered

- src/Table.tsx
修复表格数据变更后，滚动条状态异常问题
- https://github.com/react-component/table/issues/646
- https://github.com/ant-design/ant-design/issues/31319
> fix: Sync scroll bar when data change (#646)

- src/Table.tsx
> fix: sync scroll bar when `columns` changed

- src/Table.tsx
- src/utils/legacyUtil.ts
- tests/ExpandRow.spec.js
close https://github.com/ant-design/ant-design/issues/32525
> chore: warning for mix useage

- package.json
See https://github.com/JedWatson/classnames/blob/master/index.d.ts
> chore: remove unnecessary @types/classnames

- src/Table.tsx
> fix: clear ping when close horizonScroll

- src/Table.tsx
大幅优化表格默认渲染性能。
https://github.com/ant-design/ant-design/issues/33510
> perf: reduce triggerScroll call times

- src/Table.tsx
close https://github.com/ant-design/ant-design/issues/34775
> fix: table header scroll style issue

- src/Table.tsx
> fix: Remove duplicate dependencies

- src/Table.tsx
- src/utils/valueUtil.tsx
- tests/Table.spec.js
fix https://github.com/ant-design/ant-design/issues/36278
> fix: not crash on components

- docs/demo/jsx.md
- docs/examples/hover-perf.tsx
- src/Body/index.tsx
- src/Cell/index.tsx
- src/ContextSelector/index.tsx
- src/context/HoverContext.tsx
- tests/Hover.spec.tsx
resolve https://github.com/ant-design/ant-design/issues/35459
> fix: hover perf

- docs/examples/expandedRowRender.tsx
- src/Table.tsx
- src/hooks/useColumns.tsx
- src/interface.ts
- tests/ExpandRow.spec.js
Table Expand Column Title Customization
表格配置增加一个自定义columnTitle属性
ref: #853
> Table Expand Column Title Customization

- .fatherrc.ts
- docs/examples/simple.tsx
- src/Body/BodyRow.tsx
- src/Body/ExpandedRow.tsx
- src/Body/index.tsx
- src/Cell/index.tsx
- src/ContextSelector/index.tsx
- src/FixedHolder/index.tsx
- src/Footer/Cell.tsx
- src/Footer/index.tsx
- src/Header/Header.tsx
- src/Header/HeaderRow.tsx
- src/context/BodyContext.tsx
- src/context/ExpandedRowContext.tsx
- src/context/ResizeContext.tsx
- src/context/TableContext.tsx
- src/hooks/useFlattenRecords.ts
- src/stickyScrollBar.tsx
- tests/Table.spec.js
- tests/classComponent.spec.tsx
- tests/useContextSelector.spec.tsx
本来想解一下 https://github.com/ant-design/ant-design/issues/36988
感觉还是拆分多个 PR 会更好一些
> refactor: useContextSelector of all the context usage

- src/Table.tsx
fix https://github.com/ant-design/ant-design/discussions/39440
> fix: react defaultProps warning

- docs/examples/simple.tsx
- package.json
- src/Body/BodyRow.tsx
- src/Cell/index.tsx
- src/Cell/useCellRender.ts
- src/Cell/useHoverState.ts
- src/index.ts
- tests/Cell.spec.tsx
- tests/Table.spec.js
Internal state update will not re-render cell.
ref https://github.com/ant-design/ant-design/issues/36988
> refactor: Cell component with responsiveImmutable

- docs/examples/colspan-rowspan.tsx
- docs/examples/fixedColumnsAndHeader.tsx
- docs/examples/scrollY.tsx
- tests/FixedColumn-IE.spec.js
close https://github.com/react-component/table/security/code-scanning/5
close https://github.com/react-component/table/security/code-scanning/4
close https://github.com/react-component/table/security/code-scanning/3
close https://github.com/react-component/table/security/code-scanning/2
close https://github.com/react-component/table/security/code-scanning/1
> chore: fix Code scanning alerts

- src/Table.tsx
- tests/Table.spec.js
https://github.com/react-component/table/pull/966/files#r1139672299
> chore: opt for warn perf

- docs/examples/virtual.tsx
- src/FixedHolder/index.tsx
- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/BodyLine.tsx
- src/VirtualTable/context.ts
- src/VirtualTable/index.tsx
- src/context/TableContext.tsx
- src/hooks/useColumns/index.tsx
- src/hooks/useColumns/useWidthColumns.tsx
- tests/Virtual.spec.tsx
fix https://github.com/ant-design/ant-design/issues/44775
> fix: VirtualTable should force align column width

- docs/examples/scrollY.tsx
- docs/examples/virtual.tsx
- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/index.tsx
- tests/Virtual.spec.tsx
- tests/refs.spec.tsx
新的用 proxy 来处理。
ref https://github.com/ant-design/ant-design/discussions/45242
> refactor: use `ref`

- docs/examples/fixedColumns.tsx
> docs: Update fixedColumns.tsx code

- tests/Virtual.spec.tsx
> test: add test case

- package.json
Reverts react-component/table#788
> Revert "chore(deps-dev): bump react-dnd-html5-backend from 2.6.0 to 16.0.1"

- README.md
- docs/demo/column-hidden.md
- docs/demo/grouping-columns-hidden.md
- docs/examples/column-hidden.tsx
- docs/examples/grouping-columns-hidden.tsx
- src/hooks/useColumns/index.tsx
- src/interface.ts
- tests/GroupingColumns.spec.jsx
- tests/Table.spec.jsx
close: [ant-design/ant-design#46930](https://github.com/ant-design/ant-design/issues/46930)
> feat: Column add hidden

- src/Table.tsx
- src/VirtualTable/BodyGrid.tsx
- src/VirtualTable/context.ts
- src/VirtualTable/index.tsx
- tests/Table.spec.jsx
- tests/Virtual.spec.tsx
- vitest.config.ts
ref https://github.com/ant-design/ant-design/issues/44839
> feat: Table support onScroll event

- src/Body/BodyRow.tsx
- src/Cell/index.tsx
- src/Cell/useCellRender.ts
- src/FixedHolder/index.tsx
- src/VirtualTable/VirtualCell.tsx
- src/interface.ts
Follow up https://github.com/react-component/table/pull/717
原来 PR 冲突合不了了，新开一个。
close #717
resolve https://github.com/ant-design/ant-design/issues/27997
> enhance: Let `column.dataIndex` support RecordType

- src/utils/fixUtil.ts
- tests/FixedColumn.spec.tsx
- tests/__mocks__/shadowTest.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
fix https://github.com/ant-design/ant-design/issues/47835
> fix: shadow should be shown when there are columns where fixed is false

- package.json
- src/VirtualTable/BodyGrid.tsx
fix https://github.com/ant-design/ant-design/issues/47113
> fix: touch scroll should be worked when virtual

- src/namePathType.ts
ref: https://github.com/ant-design/ant-design/issues/49185
> feat: DeepNamePath deep = 5

- src/Table.tsx
- tests/Virtual.spec.tsx
- tests/__snapshots__/FixedColumn.spec.tsx.snap
fix https://github.com/react-component/table/issues/1145
快照变化了应该是上一个版本 ellipsis title 那个没有更新完全
> fix: should not reset virtual scrollLeft when data changed

- src/FixedHolder/index.tsx
- src/Table.tsx
https://github.com/ant-design/ant-design/issues/54741
> fix: show ColGroup always
